### ISSUE TITLE
WINDOWS EXE BUG

### ISSUE THREAD

**Issue by crow4586** [ionet-official/io_launch_binaries#23]
Hello author. There seems to be a bug in the WINDOWS EXE file. During deployment, the network card cannot be found error will appear. This error has occurred to many people in the DC community. I am currently deploying under UBUNTU of WSL2 and hope to solve this problem soon. Thanks.

**Comment by ilkhom19** [comment]
Please try running the latest binary from here: https://github.com/ionet-official/io_launch_binaries/releases
