### ISSUE TITLE
 In Windows 10, reconnect worker get error:  no active ethernet interface found

### ISSUE THREAD

**Issue by chencore** [ionet-official/io_launch_binaries#24]
os : window 10
error 
Warning: Please be aware that the IO Worker will stop and delete all your running Docker containers on the device.
Do you want to continue? (Yes/no): Y
Error: Error getting MAC address:  no active ethernet interface found

**Comment by microfisher** [comment]
same to me, have you fixed yet?

**Comment by ilkhom19** [comment]
can you please share your machine specs like OS and internet connection type ?

**Comment by ilkhom19** [comment]
Please try running the latest binary from here: https://github.com/ionet-official/io_launch_binaries/releases
