### ISSUE TITLE
windows:Error: Error getting MAC address

### ISSUE THREAD

**Issue by kejiyangjia** [ionet-official/io_launch_binaries#25]
Why can't users customize their secret keys on the frontend? Every time I start up, I have to go to the browser to get them, and the page easily times out or expires. The devices are also unstable, and I often need to restart them...

Warning: Please be aware that the IO Worker will stop and delete all your running Docker containers on the device.
Do you want to continue? (Yes/no): yes
Stopped container 0a44ec87dd62
Stopped container d9ddcf2db5b9

Does this system have an NVIDIA GPU which you want to use? (true/false): true
Error: Error getting MAC address:  no active ethernet interface found    
 Too stupid！！！Too stupid！！！

**Comment by beck-8** [comment]
+1

**Comment by beck-8** [comment]
same problem

**Comment by beck-8** [comment]
```powshell
Signed in as: xxx

Warning: Please be aware that the IO Worker will stop and delete all your running Docker containers on the device.
Do you want to continue? (Yes/no): yes
Error: Error getting MAC address:  no active ethernet interface found
```

**Comment by ilkhom19** [comment]
can you please share your machine specs like OS and internet connection type ?

**Comment by ilkhom19** [comment]
@kejiyangjia you can provide --token={token} for silent auth

**Comment by kejiyangjia** [comment]
> can you please share your machine specs like OS and internet connection type ?
@ilkhom19 

os: windows server 2022
gpu: nvidia A100

The server has multiple network interface cards (NICs) for outbound connections and is hosted by a cloud service provider.

**Comment by beck-8** [comment]
@kejiyangjia 
Because it will only look for the network card named ethernet, your temporary solution is to create a virtual network card named ethernet.
![image](https://github.com/ionet-official/io_launch_binaries/assets/34204218/b719efb5-be93-4758-9b55-63f5560f9c48)

**Comment by ilkhom19** [comment]
Please try running the latest binary from here: https://github.com/ionet-official/io_launch_binaries/releases
