### ISSUE TITLE
windows io_net binary file has a issue.

### ISSUE THREAD

**Issue by jangh-lee** [ionet-official/io_launch_binaries#27]
When I downloaded windows binary exe file, I got this message about virus on Windows.

Links:
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FZnyonm&threatid=2147890445

Is it okay?

**Comment by ilkhom19** [comment]
We are currently getting a certificate by Microsoft, so till then it will warn it as a virus
