### ISSUE TITLE
 Your  IO worker is launched and ready. but workers is down.

### ISSUE THREAD

**Issue by bigliang-hello** [ionet-official/io_launch_binaries#28]
*     .--.
                                / /  `
               +               | |
                      '         \ \__,
                  *          +   '--'  *
                      +   /\
         +              .'  '.
                *      /======\      +
                      ;:.  _   ;
                      |:. (_)  |
                      |:.  _   |
            +         |:. (_)  |          *
                      ;:.      ;
                    .' \:.    / `.
                   / .-'':._.'`-. \
                   |/    /||\    \|
                 _..--"""````"""--.._
           _.-'``                    ``'-._
         -'                                '-

Congratulations. Your  IO worker is launched and ready.
show me this tips.but workers is down.

**Comment by bigliang-hello** [comment]
<img width="604" alt="image" src="https://github.com/ionet-official/io_launch_binaries/assets/38687893/678ef819-c738-45d1-9ab9-1f4a0f49c491">

**Comment by ilkhom19** [comment]
Please update the binary to the latest version and try again.

use "--no_cache=true" flag to re-authenticate
