### ISSUE TITLE
Error retrieving images ... "cmd": executable file not found in %PATH%

### ISSUE THREAD

**Issue by accsanagustin** [ionet-official/io_launch_binaries#29]
I get this error after I say "Yes" to the warning to say that IO Worker will stop and delete
 Docker Containers.
 
Error retrieving images for ionetcontainers/io-worker-vc: exec: "cmd": executable file not found in %PATH%
Error retrieving images for ionetcontainers/io-worker-monitor: exec: "cmd": executable file not found in %PATH%
Error retrieving images for ionetcontainers/io-launch: exec: "cmd": executable file not found in %PATH%

**Comment by ilkhom19** [comment]
could you please manually remove old IO containers and restart ?
