### ISSUE TITLE
Error: Error getting MAC address:  no active ethernet interface found

### ISSUE THREAD

**Issue by stevenke1981** [ionet-official/io_launch_binaries#30]
Warning: Please be aware that the IO Worker will stop and delete all your running Docker containers on the device.
Do you want to continue? (Yes/no): y
Error: Error getting MAC address:  no active ethernet interface found

**Comment by ilkhom19** [comment]
can you please share your machine specs like OS and internet connection type ?

**Comment by stevenke1981** [comment]
版本	Windows 10 專業版
版本	22H2
安裝於	‎2023/‎12/‎12
OS 組建	19045.4291
體驗	Windows Feature Experience Pack 1000.19056.1000.0

**Comment by stevenke1981** [comment]
internet connection type: DHCP

**Comment by ilkhom19** [comment]
Please try running the latest binary from here: https://github.com/ionet-official/io_launch_binaries/releases
