### ISSUE TITLE
can not run worker on windows

### ISSUE THREAD

**Issue by liniukesi** [ionet-official/io_launch_binaries#37]
![image](https://github.com/ionet-official/io_launch_binaries/assets/5425209/113aff0a-7686-4731-80ce-a33d039e19a2)

**Comment by fangkj** [comment]
me too

**Comment by ilkhom19** [comment]
@liniukesi @fangkj can you guys try to open this page: https://auth0.io.solutions/activate

If that is opening, update the binary to the latest version and try again please

**Comment by wys1010** [comment]
You need to configure the agent under cmd control, as follows, and then execute the io_net_launch_binary_windows.exe file
`set http_proxy=http://127.0.0.1:7890
set https_proxy=http://127.0.0.1:7890`

**Comment by FLynnGame** [comment]
Already configure the agent. but still not working.

**Comment by mokanus** [comment]
not effect 

> 我也是

**Comment by ilkhom19** [comment]
Can you please check if you have any VPNs ?

**Comment by BlackLotusAL** [comment]
#43 This issue will help you.

**Comment by 666-arch** [comment]
> 需要在cmd控制下配置代理，如下，然后执行io_net_launch_binary_windows.exe文件
> 
> ```
> set http_proxy=http://127.0.0.1:7890
> set https_proxy=http://127.0.0.1:7890
> ```

mark
