### ISSUE TITLE
 Error authenticating: provided token has expired or invalid. Please re-authenticate using browser.

### ISSUE THREAD

**Issue by fangkj** [ionet-official/io_launch_binaries#38]
![e3baa1604fa99d6bdb0f071e4ddedb11](https://github.com/ionet-official/io_launch_binaries/assets/48847231/ef0e755d-4caf-4646-82aa-ed644003b110)

**Comment by ilkhom19** [comment]
can you guy try to open this page: https://auth0.io.solutions/activate

If that is opening, update the binary to the latest version and try again please

**Comment by nickyzhang-fe** [comment]
> can you guy try to open this page: https://auth0.io.solutions/activate
> 
> If that is opening, update the binary to the latest version and try again please

<img width="472" alt="image" src="https://github.com/ionet-official/io_launch_binaries/assets/10348941/cd03e859-1ec3-49e9-bea1-c79bab2cf234">
 what it is?

**Comment by Marginnnal** [comment]
您好，你的这个问题解决了嘛？

**Comment by TiejianZhang** [comment]
![1718285257313](https://github.com/ionet-official/io_launch_binaries/assets/32182306/19e8451b-66a6-4a2d-920c-5b08b8817d42)
I meet the same problem.

**Comment by ilkhom19** [comment]
Can you please check if you have any VPNs ?

**Comment by Jay9625** [comment]
I solve it.
You need download the latest binary, which means you should use "curl" command.
If you have network problem when using "curl -L https://github.com/ionet-official/io_launch_binaries/raw/main/io_net_launch_binary_mac -o io_net_launch_binary_mac", try to  add 
"185.199.108.133 raw.githubusercontent.com
185.199.109.133 raw.githubusercontent.com
185.199.110.133 raw.githubusercontent.com
185.199.111.133 raw.githubusercontent.com" 
to your hosts file.

**Comment by c200108** [comment]
![Uploading 0d360f8f-98ce-4a17-9ae1-2d2ccb616bcd.png…]()
请问这个怎么解决

**Comment by BlackLotusAL** [comment]
#43 This issue may help you.

**Comment by PEduck** [comment]
#43 issue can solve it. thx.
