### ISSUE TITLE
Failed to start on MAC

### ISSUE THREAD

**Issue by shadyxu** [ionet-official/io_launch_binaries#4]
I expected the following error, which seems to be related to the way you used dynamic libraries:

[43064] Error loading Python lib '/var/folders/p4/l8_3rrd91yzgpphgqkhn_zv0rkd18g/T/_MEInkazqk/libpython3.9.dylib': dlopen: dlopen(/var/folders/p4/l8_3rrd91yzgpphgqkhn_zv0rkd18g/T/_MEInkazqk/libpython3.9.dylib, 0x000A): Symbol not found: (_mkfifoat)
  Referenced from: '/private/var/folders/p4/l8_3rrd91yzgpphgqkhn_zv0rkd18g/T/_MEInkazqk/libpython3.9.dylib'
  Expected in: '/usr/lib/libSystem.B.dylib'

I found some thread, please check: https://forums.developer.apple.com/forums/thread/655588

BTW, I'm running your binary on a V12.7 MAC OS.

**Comment by icevivian** [comment]
same error

**Comment by leiweibo** [comment]
Upgrade your mac os to latest version.

**Comment by jordanjoewatson** [comment]
Had the same issue, upgraded to latest OS, problem disappeared. Ticket can be closed.

**Comment by smiraldr** [comment]
Official solution is to update macOS to sonoma
