### ISSUE TITLE
Waiting for IO containers to start...

### ISSUE THREAD

**Issue by Runer13** [ionet-official/io_launch_binaries#41]
I can not start the containers, it always try to start containers but not working. Containers are 0%.
![Ekran görüntüsü 2024-05-18 013517](https://github.com/ionet-official/io_launch_binaries/assets/107859142/711b10ce-7410-4637-9763-db6b444858a0)

**Comment by ilkhom19** [comment]
Have updated to the latest binary, and please make sure that you have a stable internet connectivity. Your output means you might have poor Network Connection

**Comment by Runer13** [comment]
Hi, my internet connection is very good and stable, and I have the latest version of binary but I still have the same issue. Waiting for IO containers to start...
I can not fix this, there for my worker is down for 5 days.

**Comment by xpfo-go** [comment]
same

**Comment by Vision0220** [comment]
same on mac mini with m2 pro

**Comment by andrewsty** [comment]
same on win10 with 4090
