### ISSUE TITLE
Error Authenticating

### ISSUE THREAD

**Issue by Austin5925** [ionet-official/io_launch_binaries#43]
After using the no_cache flag, I still cannot finish the authentication.

./io_net_launch_binary_mac --no_cache=true --device_id=10787db2-24aa-4bc5-8adc-4965e102f1c4 --user_id=5748e64a-7e32-47e4-8713-a1ccbcd1a3b0 --operating_system="macOS" --usegpus=false --device_name=ausdin-mac-new --no_cache=true
                     ____ ____      _  __ ____ ______
                    /  _// __ \    / |/ // __//_  __/
                   _/ / / /_/ /   /    // _/   / /   
                  /___/ \____/(_)/_/|_//___/  /_/

Welcome to the IO.net Launcher CLI. The ultimate tool to help you manage your IO Worker.

Current version: 2.0.6

2024/05/21 12:17:48 {
"key_set": true
}
Error: device code authorization returned: Bad Request
Error: Error authenticating: provided token has expired or invalid. Please re-authenticate using --no_cache=true flag.

**Comment by ilkhom19** [comment]
this might be the issue with Network Connections. Try to visit https://auth0.io.solutions/activate, if that doesn't open, that means Auth0 (our ID provider) is not reachable for you:

**Comment by Ionzzz** [comment]
<img width="731" alt="image" src="https://github.com/ionet-official/io_launch_binaries/assets/39758290/0410c343-214c-4527-b984-e6bd8a2a4fa1">
<img width="974" alt="image" src="https://github.com/ionet-official/io_launch_binaries/assets/39758290/862eff0f-835f-41cf-a33e-eda3bda87afc">
what is one time code, and how can i finish the authentication.

**Comment by Ionzzz** [comment]
<img width="503" alt="image" src="https://github.com/ionet-official/io_launch_binaries/assets/39758290/5e8d49c7-c341-4dbf-a1b1-def920a6b68e">
I open the TUN and manage the Service Mode, then it's ok

**Comment by Austin5925** [comment]
> this might be the issue with Network Connections. Try to visit https://auth0.io.solutions/activate, if that doesn't open, that means Auth0 (our ID provider) is not reachable for you:

The link opens. The issue is that I tried to connect to the IO, after the authentication(which succeeded), and then the CLI asked me to type "Yes"(when I left the computer for a while), and when I typed the yes, the session has already expired. the Auth0 seemed to be alright.

**Comment by ilkhom19** [comment]
please try with "--no_cache=true" flag once more

**Comment by Austin5925** [comment]
Still not working...

**Comment by FLynnGame** [comment]
Current version: 2.0.6 
it's latest version binary. but still not working.
how to run use docker cmd. i want try it.

**Comment by FLynnGame** [comment]
problem has been solved.
follow this steps.
1. Run CMD with administrator rights
2. set proxy like this
set http_proxy=http://127.0.0.1:1080
set https_proxy=http://127.0.0.1:1080
3. run cmd with your own
 io_net_launch_binary_windows.exe --device_id=xxx --user_id=xxx --operating_system="Windows" --usegpus=true --device_name="xxx"

**Comment by TiejianZhang** [comment]
> After using the no_cache flag, I still cannot finish the authentication.
> 
> ./io_net_launch_binary_mac --no_cache=true --device_id=10787db2-24aa-4bc5-8adc-4965e102f1c4 --user_id=5748e64a-7e32-47e4-8713-a1ccbcd1a3b0 --operating_system="macOS" --usegpus=false --device_name=ausdin-mac-new --no_cache=true ____ ____ _ __ ____ ______ / _// __ \ / |/ // __//_ **/ _/ / / /_/ / / // _/ / / /_**/ ____/(_)/_/|_//___/ /_/
> 
> Welcome to the IO.net Launcher CLI. The ultimate tool to help you manage your IO Worker.
> 
> Current version: 2.0.6
> 
> 2024/05/21 12:17:48 { "key_set": true } Error: device code authorization returned: Bad Request Error: Error authenticating: provided token has expired or invalid. Please re-authenticate using --no_cache=true flag.

您解决这个问题了吗

**Comment by BlackLotusAL** [comment]
> <img alt="image" width="503" src="https://private-user-images.githubusercontent.com/39758290/332497055-5e8d49c7-c341-4dbf-a1b1-def920a6b68e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NzQyMzgsIm5iZiI6MTcxODQ3MzkzOCwicGF0aCI6Ii8zOTc1ODI5MC8zMzI0OTcwNTUtNWU4ZDQ5YzctYzM0MS00ZGJmLWExYjEtZGVmOTIwYTZiNjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDE3NTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZDVlMDgyMDJhMDgyYjQ3ZjcyNTRiYjljYjI1MDhiZTk2ZDllZTQyYmM4MDA3MWY2NWQyMmZlZWNiZTk0ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qa30iTomRyB1dsPTJjplKGlWtI9iGnutiRSVlsTgyVs">

> I open the TUN and manage the Service Mode, then it's ok
Thanks God I found the solution finally.

**Comment by Daseinlux** [comment]
following steps maybe help:
1. clash enable ipv6 and tun mode。
2. tun mode: open dns ipv6 and set 8.8.8.8 the first ipv6 dns nameserver。
