### ISSUE TITLE
Waiting for IO containers to start...

### ISSUE THREAD

**Issue by aiivy782** [ionet-official/io_launch_binaries#47]
When I am starting io_net_launch_binary_windows.exe in my cmd, it creates some docker containers, they are working, but the script thinks that containers are not launched and spamming "Waiting for IO containers to start..." in cmd.

My system is Windows 11 23H2,
CPU is 12th Gen Intel(R) Core(TM) i5-12400F,
and GPU is NVIDIA GeForce RTX 3060.

I've installed Docker Desktop, but haven't installed NVIDIA CUDA Toolkit for now.

![Screenshot 2024-06-06 205117](https://github.com/ionet-official/io_launch_binaries/assets/46345948/60c46a53-f482-4824-b074-442389734f17)
![Screenshot 2024-06-06 205444](https://github.com/ionet-official/io_launch_binaries/assets/46345948/1c78d550-1491-4662-85af-c0d392facc00)

**Comment by 0xGeegZ** [comment]
Same here on MacOS M1 chips

**Comment by TcQPAD** [comment]
Exactly the same here on Windows 11 with intel GPU and RTX 3050 (GPU worker).
Was working fine BEFORE the binary was introduced, not working anymore when starting the workers from the binary.

Both IO containers are up and running (confirmed through `docker container ls --all` & in Docker Desktop UI).

**Comment by aiivy782** [comment]
Looks like I am having some progress!

I've noticed that I have installed three Docker IO images: `io-launch`, `io-worker-vc` and `io-worker-monitor`. When I am starting the script, it launches only `io-launch` and `io-worker` images, but if I'll start the `io-worker-monitor` image, the script is saying that everything is up and working.

![Screenshot 2024-06-07 170251](https://github.com/ionet-official/io_launch_binaries/assets/46345948/5a15bb18-7a08-4d60-8c24-67ecbc56786e)

There is still some thing I am nervous about tho. On the worker.io.net, in the last step of creating a worker is the button to connect  the worker. After click there is an infinite loading and in my Docker Desktop I can see that containers are not doing something, because they're not using memory or CPU, or even a GPU!

![Screenshot 2024-06-07 170341](https://github.com/ionet-official/io_launch_binaries/assets/46345948/661711e0-0009-4636-829c-2cf2e9c9cf03)

![Screenshot 2024-06-07 170203](https://github.com/ionet-official/io_launch_binaries/assets/46345948/03a97fd8-1b45-41cd-a360-362cd1d38d67)

**Comment by renguochao** [comment]
这个问题有人解决了吗？

**Comment by ilkhom19** [comment]
Overall, the script checks that all 3 containers are up and running. If it is taking too much time, it is good that you try to clear the Docker cache from your system and check connectivity issues. Also, when the worker is idle state, it doesn't use CPU or GPU, so it is normal to notice that worker is not doing anything when it is not hired

**Comment by ONLY-yours** [comment]
@aiivy782 the same as u， are u solve this problem ？ anyone can help ？

**Comment by littleboss** [comment]
in ubtuntu env, io-worker-vc container start without some env, for example "https_proxy",

**Comment by osvaldowafulua** [comment]
<img width="1512" alt="dds" src="https://github.com/user-attachments/assets/784c3058-cb3a-4a6c-bb7e-052148049d62">
I installed it on the Macbook Pro M3 Pro and AMD appears, I couldn't configure the error

**Comment by QUYNHMAI301** [comment]
I also had the same problem. How to launch rig?
![Uploading z5752049855719_94f67e7cb38a086052ee8f33e446dacb.jpg…]()
