### ISSUE TITLE
You are not the owner of the device?

### ISSUE THREAD

**Issue by k0lus** [ionet-official/io_launch_binaries#48]
Welcome to the IO.net Launcher CLI. The ultimate tool to help you manage your IO Worker.

Current version: 2.0.6

Successfully authenticated using the provided --token flag or using saved token in the cache.

Use the following token as '--token' flag for silent authentication:xxxxxxxxxxx
Refresh tokens are valid and can be reused for 365 days after being generated.
Warning: If you feel that the token has been compromised, contact IO.Net Support Team

Signed in as: xxxx@xxxxxxcom
To use Device: xxxxxxxxxxxxxxxxxxxxx

Warning: Please be aware that the IO Worker will stop and delete all your running Docker containers on the device.
Do you want to continue? (Yes/no): y

Error: You are not the owner of the device. Please use the correct deviceID and try to update the binary to the latest version.

**Comment by ilkhom19** [comment]
This happens when you created the device id with one email account, but authenticated in the terminal with different user account. Please check you account details, or try again with different device id, if that doesn't work, submit a ticket to the support team via IO.Net Intercom chat
