### ISSUE TITLE
Error: failed to validate token: expected claims not validated: go-jose/go-jose/jwt: validation field, token issued in the future (iat)

### ISSUE THREAD

**Issue by gpcoolboy** [ionet-official/io_launch_binaries#49]
____ ____      _  __ ____ ______
                    /  _// __ \    / |/ // __//_  __/
                   _/ / / /_/ /   /    // _/   / /
                  /___/ \____/(_)/_/|_//___/  /_/

Welcome to the IO.net Launcher CLI. The ultimate tool to help you manage your IO Worker.

Current version: 2.0.6

To authorise the device with IO.ID, please follow one of the options below and verify your IO.ID account:
Option 1: On your computer or mobile device navigate to: https://auth0.io.solutions/activate?user_code=XXX
Option 2: Enter the following code: XXX on: https://auth0.io.solutions/activate

Waiting for interactive authorization...

Use the following token as '--token' flag for silent authentication: XXX
Refresh tokens are valid and can be reused for 365 days after being generated.
Warning: If you feel that the token has been compromised, contact IO.Net Support Team

Signed in as: XXX@gmail.com
Error: failed to validate token: expected claims not validated: go-jose/go-jose/jwt: validation field, token issued in the future (iat)
Error: Error authenticating: provided token has expired or invalid. Please re-authenticate using --no_cache=true flag.

**Comment by ilkhom19** [comment]
Please make sure that date and time is correctly setup in your machine

**Comment by smakry** [comment]
<img width="1424" alt="image" src="https://github.com/ionet-official/io_launch_binaries/assets/31693440/364fbcec-164c-4773-8e5c-d64023eed1be">

**Comment by BlackLotusAL** [comment]
@smakry #43 This issue may help you.

**Comment by gpcoolboy** [comment]
Finally, I resolved the issue with the system time. After resynchronizing the system time, the error disappeared
