### ISSUE TITLE
How to pass in the http_proxy parameter of docker——-env

### ISSUE THREAD

**Issue by nangongchengfeng** [ionet-official/io_launch_binaries#51]
I want to use a proxy to run the program, but I am unable to add env environment parameters. Is there any related operation?
May I ask if it can be adapted and supported

**Comment by littleboss** [comment]
i met the same issue!  there are two container in linux environment, the container of ionetcontainers/io-launch is ok, but container of ionetcontainers/io-worker-vc has some issues, the docker envs (proxies) arenot in container envv

**Comment by ilkhom19** [comment]
This is not currently supported but can be something that Engineering team should think and introduce.
