### ISSUE TITLE
Always  Waiting for Device to Connect

### ISSUE THREAD

**Issue by bestK** [ionet-official/io_launch_binaries#52]
![image](https://github.com/ionet-official/io_launch_binaries/assets/14979305/831fdd6d-2bcd-4834-9509-d4b53d2472c7)
![image](https://github.com/ionet-official/io_launch_binaries/assets/14979305/72b0463f-f354-406c-827f-154b77f5623c)

**Comment by ilkhom19** [comment]
can you try to use "--no_cache=true" flag and retry ?
