### ISSUE TITLE
The container shut down automatically within ten seconds of starting

### ISSUE THREAD

**Issue by TuYv** [ionet-official/io_launch_binaries#55]
The container shut down automatically within ten seconds of starting
![image](https://github.com/ionet-official/io_launch_binaries/assets/22782479/6dd8f87d-46f7-43b6-a9ba-871597d13f3d)

**Comment by TuYv** [comment]
tried '--disable_sleep_mode=true' and '--no_cache=true' but still shut down within seconds after starting

**Comment by TuYv** [comment]
tired delete all container and binary is the latest version

**Comment by ilkhom19** [comment]
must be because of your other services interrupting the work of IO worker containers. can you please try once more, and share the device id with timestamp, @TuYv ?
