### ISSUE TITLE
Error: device code authorization returned: Bad Request

### ISSUE THREAD

**Issue by visla-jiaozebo** [ionet-official/io_launch_binaries#56]
![image](https://github.com/ionet-official/io_launch_binaries/assets/105836705/8c1c956f-8d09-4cf2-ac46-00fc36deb6bd)

**Comment by visla-jiaozebo** [comment]
It's Bad Request on **Windows terminal**, but on PowerShell and CMD, its OK. however, the nvidia-msi report error:
```shell
nvidia-smi.exe
Failed to initialize NVML: Unknown Error
```
on both PowerShell and CMD, and nvidia-msi  can work well on the Windows Terminal, which outputs:
![image](https://github.com/ionet-official/io_launch_binaries/assets/105836705/a5b54ffc-3ed3-41cc-b6d9-965b2931bae4)

**Comment by ilkhom19** [comment]
please check pinned issues and try the solutions shared there
