### ISSUE TITLE
device code authorization returned: Bad Request 

### ISSUE THREAD

**Issue by bowenhb** [ionet-official/io_launch_binaries#58]
<img width="987" alt="image" src="https://github.com/ionet-official/io_launch_binaries/assets/6073955/3298dd50-ea2d-4bd6-9065-94f5fa728aa0">

Error: device code authorization returned: Bad Request
Error: Error authenticating: provided token has expired or invalid. Please re-authenticate using --no_cache=true flag.

**Comment by bowenhb** [comment]
resolved. regarding the VPN issue,  i accessd the internet through a proxy node that i set up myself, The reason for the authentication failure is unclear, but i suspect it might be due to restrictions on the VPS line i rented. so i found a proxy that can pass the authentication, and after completing the auth, i switched back to my own proxy and it worked....

**Comment by LaHeriody** [comment]
same question, could you share your  proxy that can pass the authentication?

**Comment by ilkhom19** [comment]
please check the workaround posted in pinned issues
