### ISSUE TITLE
I couldn't configure the error

### ISSUE THREAD

**Issue by osvaldowafulua** [ionet-official/io_launch_binaries#60]
I installed it on the Macbook Pro M3 Pro and AMD appears, I couldn't configure the error
<img width="1512" alt="nsn" src="https://github.com/user-attachments/assets/a79c9ec0-dc82-4e2d-a4a3-fc61811c2690">
<img width="1512" alt="dds" src="https://github.com/user-attachments/assets/0740f608-d916-4d29-a7f7-5360558576ac">

**Comment by ilkhom19** [comment]
can you please clear all docker cache, images, and try again please. Also share device id with the timestamp of the try
